version: '3.7'

services:
  ### MongoDB ##############################################
  mongodb:
    image: mongo:latest
    container_name: empire-future-mongodb
    volumes:
      - ./db_data/mongo/:/data/db
      - ./db_data/mongo_dumps/:/data/dumps
    networks:
      - mongodb
    ports:
      - '27017:27017'
    user: '1000:1000'

  ### Redis ################################################

  ### PostgreSQL ###########################################

  ### RabbitMQ #############################################

networks:
  mongodb:
    driver: bridge

volumes:
  mongodb:
  mongodb_dumps: